version: '3'

services:
  frontend:
    container_name: blog_frontend
    image: blog_frontend
    restart: always
    build: ./
    ports: 
      - "3000:3000"
    networks:
      - spring_frontend 

networks:
  spring_frontend:
    name: spring_frontend
    driver: bridge     